spring:
  profiles:
    active: local
    group:
      local: console-logging
      prod: real-slack, file-info-logging, file-error-logging, slack-prod-error-logging
---
spring:
  config:
    activate:
      on-profile: local
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
        default_batch_fetch_size: 100
    show-sql: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:cryptohows
    username: sa
    password:
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
upload:
  password: cryptohows
swagger-docs:
  url: http://localhost:8080
---
spring:
  config:
    activate:
      on-profile: test
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
        default_batch_fetch_size: 100
    show-sql: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:cryptohows
    username: sa
    password:
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
upload:
  password: cryptohows
swagger-docs:
  url: http://localhost:8080
---
spring:
  config:
    activate:
      on-profile: prod
logging:
  file:
    path: /home/ubuntu/
swagger-docs:
  url: https://api.cryptohows.xyz
---
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        default_batch_fetch_size: 100
    show-sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgres://gryvkgujwvzfrg:83ab29e1edc3d237862a6a8f8cd3ff842965afc98ef581c1baf6c4663c4e2090@ec2-3-212-45-192.compute-1.amazonaws.com:5432/d5guh38oijobj
    username: gryvkgujwvzfrg
    password: 83ab29e1edc3d237862a6a8f8cd3ff842965afc98ef581c1baf6c4663c4e2090
    port: 5432
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
upload:
  password: cryptohows
server:
  port: ${PORT:8080}
swagger-docs:
  url: https://cryptohows.herokuapp.com
---
springdoc:
  version: 1.0.0
  swagger-ui:
    path: index.html
